name: Docker Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  docker-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: pulso-web:latest
          cache-from: type=gha,scope=web
          cache-to: type=gha,mode=max,scope=web
